name: Single-Module Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main-workflow:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source code from Github
        uses: actions/checkout@v3

      - uses: ./composite
